### ISSUE TITLE
Support POST object

### ISSUE THREAD

**Issue by kellymclaughlin** [basho/riak_cs#162]
http://docs.amazonwebservices.com/AmazonS3/latest/API/RESTObjectPOST.html

**Comment by reiddraper** [comment]
I believe we fixed this in 1.1, yeah?

**Comment by kuenishi** [comment]
Uh, it looks not fixed :'( => https://github.com/basho/riak_cs/blob/master/src/riak_cs_wm_key.erl#L154

**Comment by reiddraper** [comment]
Looks like you're correct.

**Comment by reiddraper** [comment]
been finding [this page](http://www.w3.org/TR/html401/interact/forms.html) useful in doing research on this ticket

**Comment by kuenishi** [comment]
We already have 1.2 released, and POST is not in urgent need - so I'm gonna remove this ticket from Milestone 1.2.0.
